backend:
  name: github
  repo: p1t1ch/personal-blog

media_folder: static/assets
public_folder: /assets

publish_mode: editorial_workflow
site_url: https://p1t1ch-personal-blog.netlify.app

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{fields.slug}}'
    preview_path: 'blog/{{fields.slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', dateFormat: 'DD.MM.YYYY', timeFormat: false }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Unsplash Credits', name: 'unsplashCredits', widget: 'text' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
